### ISSUE TITLE
Service Versioning

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_runtime#72]
## Requirements
1. Runtime contains a versioning file, that holds the most recent version of each service
1. Script updates running service based on the version file.
2. Service has a Workflow that updates the version file.
    - e2e tests must pass

### Tasks
- [x] Version file in runtime (updated with git pull)
- [x] Script to update .env and running services
- [x] Action to auto-version
- [x] Write Documentation
